#!/usr/bin/env python3
"""Train a small neural Q-network from World2Work navigation experience.

This is an offline fitted-DQN baseline. It consumes the JSONL transitions
generated by ``train_nav_qlearning.py``, aggregates repeated deterministic
state/action samples, and fits a two-layer ReLU Q-network to Bellman targets.
No pretrained checkpoint is used; the comparison is randomly initialized
network versus the same network after environment-conditioned training.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

import numpy as np

from train_nav_qlearning import ACTIONS, bfs_distance, transition


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def stable_argmax(values: np.ndarray) -> int:
    # np.argmax returns the first maximum, matching the tabular policy tie-break.
    return int(np.argmax(values))


class NeuralQNetwork:
    """One-hidden-layer ReLU Q-network implemented in NumPy."""

    def __init__(self, input_dim: int, hidden_dim: int, actions: int, seed: int) -> None:
        rng = np.random.default_rng(seed)
        self.params = {
            "w1": rng.normal(0.0, math.sqrt(2.0 / input_dim), (input_dim, hidden_dim)),
            "b1": np.zeros(hidden_dim, dtype=np.float64),
            "w2": rng.normal(0.0, math.sqrt(2.0 / hidden_dim), (hidden_dim, actions)),
            "b2": np.zeros(actions, dtype=np.float64),
        }
        self.m = {name: np.zeros_like(value) for name, value in self.params.items()}
        self.v = {name: np.zeros_like(value) for name, value in self.params.items()}
        self.adam_step = 0

    def copy_params(self) -> dict[str, np.ndarray]:
        return {name: value.copy() for name, value in self.params.items()}

    def predict(self, x: np.ndarray, params: dict[str, np.ndarray] | None = None) -> np.ndarray:
        p = params or self.params
        # NumPy 2.0 + Accelerate on some macOS hosts emits spurious floating
        # warnings for finite matmul results; validate the result explicitly.
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            hidden = np.maximum(0.0, x @ p["w1"] + p["b1"])
            result = hidden @ p["w2"] + p["b2"]
        if not np.all(np.isfinite(result)):
            raise FloatingPointError("non-finite Q-network prediction")
        return result

    def train_step(
        self,
        x: np.ndarray,
        target: np.ndarray,
        weights: np.ndarray,
        learning_rate: float,
    ) -> float:
        p = self.params
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            z1 = x @ p["w1"] + p["b1"]
            hidden = np.maximum(0.0, z1)
            predicted = hidden @ p["w2"] + p["b2"]
            error = predicted - target
            normalizer = float(np.sum(weights))
            loss = float(np.sum(weights * error * error) / normalizer)
            grad_q = (2.0 / normalizer) * weights * error
            grads = {
                "w2": hidden.T @ grad_q,
                "b2": np.sum(grad_q, axis=0),
            }
            grad_hidden = grad_q @ p["w2"].T
            grad_z1 = grad_hidden * (z1 > 0.0)
            grads["w1"] = x.T @ grad_z1
            grads["b1"] = np.sum(grad_z1, axis=0)
        if not math.isfinite(loss) or not all(
            np.all(np.isfinite(grad)) for grad in grads.values()
        ):
            raise FloatingPointError("non-finite DQN loss or gradient")

        global_norm = math.sqrt(
            sum(float(np.sum(grad * grad)) for grad in grads.values())
        )
        if global_norm > 5.0:
            scale = 5.0 / global_norm
            grads = {name: grad * scale for name, grad in grads.items()}

        self.adam_step += 1
        beta1, beta2, epsilon = 0.9, 0.999, 1e-8
        for name, grad in grads.items():
            self.m[name] = beta1 * self.m[name] + (1.0 - beta1) * grad
            self.v[name] = beta2 * self.v[name] + (1.0 - beta2) * (grad * grad)
            m_hat = self.m[name] / (1.0 - beta1**self.adam_step)
            v_hat = self.v[name] / (1.0 - beta2**self.adam_step)
            p[name] -= learning_rate * m_hat / (np.sqrt(v_hat) + epsilon)
        return loss


def load_experience(
    path: Path,
    state_index: dict[tuple[int, int], int],
    goal: tuple[int, int],
) -> tuple[np.ndarray, np.ndarray, np.ndarray, int, np.ndarray, int]:
    """Aggregate raw JSONL while retaining the exact source transition count."""
    state_count = len(state_index)
    reward_sum = np.zeros((state_count, 4), dtype=np.float64)
    counts = np.zeros((state_count, 4), dtype=np.int64)
    next_indices = np.full((state_count, 4), -1, dtype=np.int64)
    success_terminal = np.zeros((state_count, 4), dtype=np.float64)
    transition_count = 0
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            item = json.loads(line)
            state = tuple(int(value) for value in item["state"])
            next_state = tuple(int(value) for value in item["next_state"])
            action = int(item["action"])
            if state not in state_index or next_state not in state_index:
                raise ValueError(f"unknown state at JSONL line {line_number}")
            row = state_index[state]
            next_row = state_index[next_state]
            previous_next = int(next_indices[row, action])
            if previous_next not in (-1, next_row):
                raise ValueError(
                    f"non-deterministic next state for {state}, action {action}"
                )
            next_indices[row, action] = next_row
            reward_sum[row, action] += float(item["reward"])
            counts[row, action] += 1
            # Time-limit truncation is not a terminal MDP state. Goal success is.
            success_terminal[row, action] += float(bool(item.get("success")))
            transition_count += 1
    source_bin_count = int(np.sum(counts > 0))
    rewards = np.divide(
        reward_sum,
        counts,
        out=np.zeros_like(reward_sum),
        where=counts > 0,
    )
    terminals = np.divide(
        success_terminal,
        counts,
        out=np.zeros_like(success_terminal),
        where=counts > 0,
    )
    # The goal is absorbing and episodes stop on entry, so it correctly has no
    # outgoing samples in JSONL. Add a zero-value absorbing row for fitting.
    goal_row = state_index[goal]
    counts[goal_row, :] = 1
    next_indices[goal_row, :] = goal_row
    terminals[goal_row, :] = 1.0
    if np.any(counts == 0):
        missing = int(np.sum(counts == 0))
        raise ValueError(f"offline dataset is missing {missing} state/action bins")
    return rewards, next_indices, terminals, transition_count, counts, source_bin_count


def evaluate_network(
    network: NeuralQNetwork,
    features: np.ndarray,
    configurations: list[dict[str, Any]],
    goal: tuple[int, int],
    free: set[tuple[int, int]],
    state_index: dict[tuple[int, int], int],
    label: str,
) -> dict[str, Any]:
    q_values = network.predict(features)
    action_for_name = {action["name"]: action["id"] for action in ACTIONS}
    results: list[dict[str, Any]] = []
    total_actions = 0
    total_collisions = 0
    collision_episodes = 0
    successes = 0
    efficiencies: list[float] = []
    for config in configurations:
        state = tuple(int(value) for value in config["start_cell"])
        heading = action_for_name[config["initial_orientation"]]
        initial_heading = heading
        shortest = int(config["shortest_path_steps"])
        max_steps = max(60, min(300, shortest * 6))
        collisions = 0
        quarter_turns = 0
        visited_cells = [list(state)]
        success = False
        for step in range(1, max_steps + 1):
            action = stable_argmax(q_values[state_index[state]])
            turn = abs(action - heading)
            quarter_turns += min(turn, 4 - turn)
            heading = action
            state, collision = transition(state, action, free)
            collisions += int(collision)
            visited_cells.append(list(state))
            if state == goal:
                success = True
                break
        actual_steps = step
        efficiency = shortest / max(actual_steps, shortest) if success else None
        if efficiency is not None:
            efficiencies.append(efficiency)
        successes += int(success)
        total_actions += actual_steps
        total_collisions += collisions
        collision_episodes += int(collisions > 0)
        results.append(
            {
                "episode": int(config["episode"]),
                "start_cell": list(config["start_cell"]),
                "initial_orientation": ACTIONS[initial_heading]["name"],
                "final_orientation": ACTIONS[heading]["name"],
                "shortest_path_steps": shortest,
                "actual_steps": actual_steps,
                "success": success,
                "collision_actions": collisions,
                "quarter_turns": quarter_turns,
                "path_efficiency": round(efficiency, 6) if efficiency is not None else None,
                "termination": "goal" if success else "timeout",
                "visited_cells": visited_cells,
            }
        )
    count = len(results)
    return {
        "policy": label,
        "episodes": results,
        "metrics": {
            "success_rate": round(successes / count, 6),
            "collision_rate": round(total_collisions / max(1, total_actions), 6),
            "path_efficiency": (
                round(sum(efficiencies) / len(efficiencies), 6)
                if efficiencies
                else None
            ),
            "successful_episodes": successes,
            "total_episodes": count,
            "total_actions": total_actions,
            "collision_actions": total_collisions,
            "collision_episode_rate": round(collision_episodes / count, 6),
            "mean_quarter_turns": round(
                sum(item["quarter_turns"] for item in results) / count, 6
            ),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nav-dir", default="artifacts/corgi-cafe/nav")
    parser.add_argument("--target", default="table_7")
    parser.add_argument("--seed", type=int, default=20260905)
    parser.add_argument("--hidden-dim", type=int, default=96)
    parser.add_argument("--bellman-iterations", type=int, default=400)
    parser.add_argument("--gradient-steps", type=int, default=20)
    parser.add_argument("--learning-rate", type=float, default=0.001)
    parser.add_argument("--gamma", type=float, default=0.97)
    args = parser.parse_args()

    nav_dir = Path(args.nav_dir)
    grid = load_json(nav_dir / "occupancy_grid.json")
    meta = load_json(nav_dir / "grid_meta.json")
    reference_evaluation = load_json(nav_dir / "evaluation_summary.json")
    cells = grid["cells"]
    rows, cols = int(grid["rows"]), int(grid["cols"])
    free = {
        (row, col)
        for row in range(rows)
        for col in range(cols)
        if cells[row][col] == grid["free_value"]
    }
    states = sorted(free)
    state_index = {state: index for index, state in enumerate(states)}
    goal = tuple(int(value) for value in meta["targets"][args.target]["cell"])
    distance = bfs_distance(goal, free)
    configurations = reference_evaluation["holdout"]["configurations"]

    rewards, next_indices, terminals, transition_count, counts, source_bin_count = load_experience(
        nav_dir / "training_experience.jsonl", state_index, goal
    )
    features = np.eye(len(states), dtype=np.float64)
    network = NeuralQNetwork(len(states), args.hidden_dim, 4, args.seed)
    untrained = evaluate_network(
        network,
        features,
        configurations,
        goal,
        free,
        state_index,
        "greedy policy from randomly initialized neural Q-network",
    )

    # Each state/action bin participates in every fitted Bellman update. Counts
    # sum to the raw 94,906-transition dataset and provide a mild confidence
    # weight without allowing common transitions to erase rare actions.
    weights = np.sqrt(counts.astype(np.float64))
    weights /= float(np.mean(weights))
    target_params = network.copy_params()
    curve: list[dict[str, Any]] = []
    latest_loss = float("nan")
    for iteration in range(1, args.bellman_iterations + 1):
        target_q = network.predict(features, target_params)
        best_next = np.max(target_q[next_indices], axis=2)
        bellman = rewards + args.gamma * (1.0 - terminals) * best_next
        bellman = np.clip(bellman, -100.0, 100.0)
        for _ in range(args.gradient_steps):
            latest_loss = network.train_step(
                features,
                bellman,
                weights,
                args.learning_rate,
            )
        target_params = network.copy_params()
        if not all(np.all(np.isfinite(value)) for value in target_params.values()):
            raise FloatingPointError("non-finite neural-network parameter")
        if iteration == 1 or iteration % 10 == 0 or iteration == args.bellman_iterations:
            evaluation = evaluate_network(
                network,
                features,
                configurations,
                goal,
                free,
                state_index,
                "greedy policy from trained neural Q-network",
            )
            curve.append(
                {
                    "bellman_iteration": iteration,
                    "gradient_updates": iteration * args.gradient_steps,
                    "weighted_mse": round(latest_loss, 8),
                    **evaluation["metrics"],
                }
            )

    trained = evaluate_network(
        network,
        features,
        configurations,
        goal,
        free,
        state_index,
        "strict argmax over environment-trained neural Q-network",
    )
    before = untrained["metrics"]
    after = trained["metrics"]

    q_values = network.predict(features)
    policy = [[-1] * cols for _ in range(rows)]
    exported_q: dict[str, list[float]] = {}
    for state in states:
        values = q_values[state_index[state]]
        policy[state[0]][state[1]] = stable_argmax(values)
        exported_q[f"{state[0]},{state[1]}"] = [round(float(v), 6) for v in values]
    model_path = nav_dir / f"dqn_{args.target}.npz"
    np.savez_compressed(model_path, **network.params)
    policy_payload = {
        "schema_version": "world2work.neural-q-policy.v1",
        "algorithm": "offline_fitted_dqn",
        "network": {
            "input": f"one-hot grid state ({len(states)} reachable cells)",
            "hidden": f"Dense({args.hidden_dim}) + ReLU",
            "output": "Dense(4) Q-values",
            "parameter_count": int(sum(value.size for value in network.params.values())),
            "pretrained_checkpoint": None,
            "initialization": "random",
        },
        "target_id": args.target,
        "seed": args.seed,
        "actions": ACTIONS,
        "rows": rows,
        "cols": cols,
        "policy": policy,
        "q_values": exported_q,
        "checkpoint": model_path.name,
        "training": {
            "experience_file": "training_experience.jsonl",
            "raw_transition_count": transition_count,
            "aggregated_state_action_bins": source_bin_count,
            "bellman_iterations": args.bellman_iterations,
            "gradient_updates": args.bellman_iterations * args.gradient_steps,
            "gamma": args.gamma,
            "learning_rate": args.learning_rate,
            "note": "Repeated deterministic samples are aggregated; bin counts sum to raw_transition_count and weight the loss.",
        },
    }
    (nav_dir / f"dqn_policy_{args.target}.json").write_text(
        json.dumps(policy_payload, indent=2) + "\n", encoding="utf-8"
    )
    curve_payload = {
        "schema_version": "world2work.dqn-learning-curve.v1",
        "algorithm": "offline_fitted_dqn",
        "target_id": args.target,
        "seed": args.seed,
        "raw_transition_count": transition_count,
        "points": curve,
    }
    (nav_dir / "dqn_learning_curve.json").write_text(
        json.dumps(curve_payload, indent=2) + "\n", encoding="utf-8"
    )
    evaluation_payload = {
        "schema_version": "world2work.dqn-policy-evaluation.v1",
        "target_id": args.target,
        "seed": args.seed,
        "training_data": {
            "file": "training_experience.jsonl",
            "raw_transition_count": transition_count,
        },
        "comparison_label": "randomly initialized network vs environment-trained network",
        "pretrained_model_used": False,
        "holdout": reference_evaluation["holdout"],
        "metric_definitions": reference_evaluation["metric_definitions"],
        "policies": {
            "before_training_random_init": untrained,
            "after_training_dqn": trained,
        },
        "comparison": {
            "success_rate_delta": round(after["success_rate"] - before["success_rate"], 6),
            "collision_rate_delta": round(after["collision_rate"] - before["collision_rate"], 6),
            "path_efficiency_delta": (
                round(after["path_efficiency"] - before["path_efficiency"], 6)
                if after["path_efficiency"] is not None
                and before["path_efficiency"] is not None
                else None
            ),
        },
    }
    (nav_dir / "dqn_evaluation_summary.json").write_text(
        json.dumps(evaluation_payload, indent=2) + "\n", encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "status": "DQN_OK",
                "algorithm": "offline_fitted_dqn",
                "training_transitions": transition_count,
                "network_parameters": policy_payload["network"]["parameter_count"],
                "held_out_episodes": len(configurations),
                "before_training_metrics": before,
                "after_training_metrics": after,
                "checkpoint": str(model_path),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"DQN_ERROR: {exc}", file=sys.stderr)
        raise
